Fix for zeromq_pub module: change from dict comprehesion to generator expression with dict constructor, otherwise not supported in Python 2.6
SyntaxError: ('invalid syntax', ('./zeromq_pub/python_modules/zpubmon.py', 81, 26, '    counter = {name: 0 for name in params}\n'))