Custom mysql port and timeout integer fix
When mysql.pyconf configured with custom port:

    param port {
      value = 3307
    }

gmond gives into log:
[PYTHON] Can't call the metric_init function in the python module [mysql].#012

and further investigation with
*gmond -d 1*
shows

[PYTHON] Can't call the metric_init function in the python module [mysql].
Traceback (most recent call last):
  File "/usr/lib64/ganglia/python_modules/mysql.py", line 1005, in metric_init
    update_stats(REPORT_INNODB, REPORT_MASTER, REPORT_SLAVE)
  File "/usr/lib64/ganglia/python_modules/mysql.py", line 86, in update_stats
    conn = MySQLdb.connect(**mysql_conn_opts)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required

Method params.get converted explicitly as integer with timeout and port option.